version: 2

models:
  - name: silver_listings
    description: "Table Silver nettoyee et enrichie des annonces immobilieres"
    columns:
      - name: listing_id
        description: "Identifiant unique de l'annonce"
        tests:
          - unique
          - not_null
      - name: property_type
        description: "Type de bien immobilier"
        tests:
          - not_null
          - accepted_values:
              values: ['apartment', 'house', 'villa', 'studio', 'duplex', 'penthouse']
      - name: country
        description: "Pays du bien"
        tests:
          - not_null
      - name: city
        description: "Ville du bien"
        tests:
          - not_null
      - name: neighborhood
        description: "Quartier du bien"
        tests:
          - not_null
      - name: surface_m2
        description: "Surface en m2"
        tests:
          - not_null
      - name: num_rooms
        description: "Nombre de pieces"
        tests:
          - not_null
      - name: num_bathrooms
        description: "Nombre de salles de bain"
        tests:
          - not_null
      - name: floor
        description: "Etage"
        tests:
          - not_null
      - name: year_built
        description: "Annee de construction"
        tests:
          - not_null
      - name: price
        description: "Prix de vente"
        tests:
          - not_null
      - name: listing_date
        description: "Date de publication"
        tests:
          - not_null
      - name: condition
        description: "Etat du bien"
        tests:
          - not_null
          - accepted_values:
              values: ['New', 'Good', 'Renovated', 'Old']
      - name: heating_type
        description: "Type de chauffage"
        tests:
          - not_null
      - name: parking
        description: "Disponibilite parking"
        tests:
          - not_null
          - accepted_values:
              values: ['YES', 'NO', 'UNKNOWN']
      - name: energy_rating
        description: "Classe energetique"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C', 'D', 'E', 'F', 'G']
      - name: property_age
        description: "Age du bien en annees"
        tests:
          - not_null
      - name: price_per_m2
        description: "Prix au m2"
        tests:
          - not_null
