name: 'real_estate_silver'
version: '1.0.0'

profile: 'real_estate_silver'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  real_estate_silver:
    +materialized: table

    gold:
      +schema: GOLD
      +materialized: table