USE DATABASE REAL_ESTATE_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE RAW_REAL_ESTATE (
    LISTING_ID INTEGER,
    PROPERTY_TYPE STRING,
    COUNTRY STRING,
    CITY STRING,
    NEIGHBORHOOD STRING,
    SURFACE_M2 FLOAT,
    NUM_ROOMS FLOAT,
    NUM_BATHROOMS FLOAT,
    FLOOR FLOAT,
    YEAR_BUILT FLOAT,
    PRICE STRING,
    LISTING_DATE STRING,
    CONDITION STRING,
    HEATING_TYPE STRING,
    PARKING STRING,
    ENERGY_RATING STRING,
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);