USE DATABASE REAL_ESTATE_DB;
USE SCHEMA BRONZE;

COPY INTO RAW_REAL_ESTATE
(
    LISTING_ID,
    PROPERTY_TYPE,
    COUNTRY,
    CITY,
    NEIGHBORHOOD,
    SURFACE_M2,
    NUM_ROOMS,
    NUM_BATHROOMS,
    FLOOR,
    YEAR_BUILT,
    PRICE,
    LISTING_DATE,
    CONDITION,
    HEATING_TYPE,
    PARKING,
    ENERGY_RATING
)
FROM @RAW_STAGE
FILES = ('real-estate-raw-6a3e627c94437783777235.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');