real_estate:
  outputs:
    dev:
      account: wy52468.eu-west-3.aws
      database: REAL_ESTATE_DB
      password: MagnusCarlsen0109817er@r
      role:  ACCOUNTADMIN
      schema: public
      threads: 1
      type: snowflake
      user: zakariadev
      warehouse: REAL_ESTATE_WH
  target: dev
